# Generated by Django 2.1.4 on 2019-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitek', '0009_startbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='start_balance',
        ),
        migrations.RemoveField(
            model_name='place',
            name='start_balance_currency',
        ),
        migrations.AddField(
            model_name='place',
            name='start_balances',
            field=models.ManyToManyField(to='vitek.StartBalance'),
        ),
    ]
